_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
#  WEIGHTS: "E:/y/ori-code/detectron2-main/models/mobilenet_v3_detectron2.pth"
  WEIGHTS: "E:/y/ori-code/detectron2-main/models/mbv2_ca_detectron2.pth"
#  WEIGHTS: "E:/y/ori-code/detectron2-main/models/efficientnet-b0_detectron2.pth"
#  WEIGHTS: "E:/y/ori-code/detectron2-main/results/final/ex2/model_final.pth"
  MASK_ON: True
  EFFICIENTNET:
    NAME: "efficientnet-b0"
  RESNETS:
    DEPTH: 50
#    DEFORM_ON_PER_STAGE: [False, True, True, True ] # on Res3,Res4,Res5
#    DEFORM_MODULATED: False
#    NORM: "GN"
#    STRIDE_IN_1X1: False
#  FPN:
#    NORM: "GN"
  ROI_HEADS:
#    NAME: "BoundaryROIHeads"
    NAME: "PatchDCTROIHeads"
    NUM_CLASSES: 68
#  ROI_MASK_HEAD:
#      NAME: "BoundaryDICEHead"
#
#  DYHEAD:
#    NUM_CONVS: 6
#    CHANNELS: 256
#  ROI_BOX_HEAD:
#    NAME: "FastRCNNConvFCHead"
#    NUM_CONV: 4
#    NUM_FC: 1
#    NORM: "GN"
#    BBOX_REG_LOSS_TYPE: "giou"
  ########################### dct-mask
#  ROI_MASK_HEAD:
#    NAME: "MaskRCNNDCTHead"
#    DCT_VECTOR_DIM: 300
#    MASK_SIZE: 128
#    MASK_LOSS_PARA: 0.007
#    DCT_LOSS_TYPE: "l2"
  ######################### patch-dct
  ROI_MASK_HEAD:
    NAME: "MaskRCNNPatchDCTHead"
    NUM_CONV: 4
    CLS_AGNOSTIC_MASK: False
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    POOLER_RESOLUTION: 14
    FINE_FEATURES: [ "p2" ]
    FINE_FEATURES_RESOLUTION: 42
    MASK_SIZE: 112
    DCT_VECTOR_DIM: 300
    MASK_SIZE_ASSEMBLE: 112
    PATCH_SIZE: 8
    PATCH_DCT_VECTOR_DIM: 6
    MASK_LOSS_PARA: 1.0
    HIDDEN_FEATURES: 1024
    PATCH_THRESHOLD: 0.30
    NUM_STAGE: 2 #include DCT stage, should be PatchDCT N_Stage+1
    MASK_LOSS_PARA_EACH_STAGE: [ 1.0, 1.0 ]
    EVAL_GT: False # Only set to be "True" for upper bound evaluation
    DCT_LOSS_TYPE: "l1"
  BACKBONE:
#    NAME: "build_efficientnet_pafpn_backbone"
    NAME: "build_mnv2_ca_iePAfpn_backbone"
#    NAME: "build_mnv2_ca_iefpn_backbone"
#    NAME: "build_mnv2_ca_fpn_backbone"
#    NAME: "build_mnv3l_pafpn_backbone"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
#  STEPS: (6000, 8000)
#  MAX_ITER: 9000
#  CHECKPOINT_PERIOD: 3000
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 3000
TEST:
  EVAL_PERIOD: 3000
#OUTPUT_DIR: "./results/small/ex13"
OUTPUT_DIR: "../results/final/ex4"